version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: scrapper
    volumes:
      - pg-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - postgres
    command:
      - --hub-mode=off
      - --changelog-file=./master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgres:5432/scrapper
      - --username=root
      - --password=root
      - update
    volumes:
      - ./:/liquibase/changelog
    networks:
      - backend

volumes:
  pg-data:

networks:
  backend: { }
